### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pexcn** [pexcn/static-build-ci#5]
- [ ] ~~不要全部静态链接，仅链接第三方库就好了 (try again)~~
- [ ] x86_64 -> amd64
- [ ] ~~ss-server: add dscp option? `apt-get install libnetfilter-conntrack-dev`~~
- [ ] ~~libsodium: try --enable-opt, release two version~~

**Comment by pexcn** [comment]
libsodium: try --enable-opt, release two version

**Comment by pexcn** [comment]
https://github.com/shadowsocks/openwrt-feeds/blob/f820447956c77a412a694022d91c4b812f216d47/packages/pcre/Makefile#L41-L45
```bash
# pcre
--enable-utf8
--enable-unicode-properties
--enable-pcre16
--with-match-limit-recursion=16000
```
